### ISSUE TITLE
Removing shape after selecting for linking / dependent premise causes problems

### ISSUE THREAD

**Issue by joekrystowski** [joekrystowski/Argument-Diagram#20]
Removing a shape while it is in the queue to be linked or combined into a dependent premise causes problems because it is not removed from the queue.

**To Reproduce**
1. Select a shape for linking
2. delete that shape
3. now select a second shape for linking

**Expected behavior**
A shape should be removed from the linking and dependent premise queues after being removed

**Comment by eddiekrystowski** [comment]
I believe this has been fixed by #45
