### ISSUE TITLE
Customize spawn location for shapes on paper

### ISSUE THREAD

**Issue by joekrystowski** [joekrystowski/Argument-Diagram#27]
**Describe the feature you'd like**
It might be helpful for users to be able to determine where they want to spawn their shapes.

Perhaps there could be some kind of interface to see default values of a shape when it is spawned in, like its text contents, size, spawn location, etc.

Or possible we could have them drag and drop the shape onto the paper.. not sure how it would be done but see the demo for Rappid.js to see what I mean.

**Comment by eddiekrystowski** [comment]
Something to consider: Perhaps we could add a feature where the user does a drag and drop of a shape from the menu on to the paper. That way they get to choose where it shows up and it will always show up on the paper.
