### ISSUE TITLE
Improve text alignment for dependent premise

### ISSUE THREAD

**Issue by joekrystowski** [joekrystowski/Argument-Diagram#28]
Currently the left and right sides of a dependent premise are left and right justified, respectively. It might be better to have each line centered within its given width, especially when we start nesting dependent premises.

**Comment by eddiekrystowski** [comment]
Not sure how much work has been done here already, but make sure you have pulled in changes from #35 to try and avoid conflicts

**Comment by joekrystowski** [comment]
Closing this issue because it is not longer relevant after dependent premise rework #58
