### ISSUE TITLE
Organize css

### ISSUE THREAD

**Issue by joekrystowski** [joekrystowski/Argument-Diagram#30]
The css is pretty disorganized, would be a good idea to organize it into sections so things will be easier to find later on.

**Comment by eddiekrystowski** [comment]
Also, creating variables for colors is important to make sure they are standardized across the site and they are easy to change. We should also consider making a css directory in the public folder and separating out css into separate files where reasonable.

**Comment by skpandey885** [comment]
hey, Can I Fix This One? Waiting For A positive Reply

**Comment by joekrystowski** [comment]
> hey, Can I Fix This One? Waiting For A positive Reply

Hi, @skpandey885, currently we are not looking for additional contributors to this project. Thank you for your interest, I can let you know if this changes.

**Comment by joekrystowski** [comment]
Closing this for now, we moved to SCSS and it has more or less been organized
