### ISSUE TITLE
No circular arguments

### ISSUE THREAD

**Issue by eddiekrystowski** [joekrystowski/Argument-Diagram#36]
**Describe the bug**
Right now, there are no checks in place to stop circular arguments

**To Reproduce**
1. Connect 3 arguments in a triangle
2. See error

**Expected behavior**
When trying to connect the last link that would make a circular argument, it should not allow the link to be made and give some kind of error alert to the user.

**Comment by joekrystowski** [comment]
Not sure exactly how much this will help, but if you are working on this take a look at 

https://resources.jointjs.com/docs/jointjs/v3.3/joint.html#dia.Graph.prototype.getConnectedLinks

you can obviously use it to get the links coming off of an element. Additionally, the "deep" option looks interesting and may save some time on this problem depending on how exactly it works (still not sure myself). I would look into it.
